openapi: 3.0.1
info:
  title: Google Sheets Logger
  description: Plugin לשליחת תיעוד ל-Google Sheets דרך Cloudflare Worker
  version: 1.0.0
servers:
  - url: https://gpt-to-sheets.sapirubner10.workers.dev
paths:
  /:
    post:
      summary: שלח תיעוד
      operationId: sendLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                title:
                  type: string
                content:
                  type: string
                category:
                  type: string
                source:
                  type: string
                mode:
                  type: string
                track:
                  type: string
      responses:
        '200':
          description: נשלח בהצלחה
