openapi: 3.1.0
info:
  title: Google Sheets Logger
  description: Plugin לשליחת תיעוד ורפלקציה ל-Google Sheets דרך Cloudflare Worker
  version: 1.0.1
servers:
  - url: https://gpt-to-sheets.sapirubner10.workers.dev
paths:
  /:
    post:
      summary: שלח תובנה או רפלקציה ל-Google Sheets
      operationId: sendLog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: ["log", "reflection"]
                  description: סוג הרשומה – תובנה רגילה או רפלקציה
                date:
                  type: string
                  description: תאריך הרישום (YYYY-MM-DD)
                title:
                  type: string
                  description: כותרת קצרה לתובנה (רק עבור log)
                content:
                  type: string
                  description: גוף התובנה או הטקסט (רק עבור log)
                category:
                  type: string
                  description: תחום חיים (SELF, FLOW וכו’) (רק עבור log)
                source:
                  type: string
                  description: מקור התובנה (Reflection, Critique וכו’) (log בלבד)
                mode:
                  type: string
                  description: מצב החיים הפעיל (רק עבור log)
                track:
                  type: string
                  enum: ["כן", "לא"]
                  description: האם לעקוב (log בלבד)
                engines_used:
                  type: object
                  description: מיפוי הפעלות מנועים (reflection בלבד)
                  properties:
                    Verifier: { type: string }
                    Critique: { type: string }
                    Reflection: { type: string }
                    Innovation: { type: string }
                inactive_engines:
                  type: array
                  description: מנועים שלא הופעלו (reflection בלבד)
                  items: { type: string }
                ignored_suggestions:
                  type: array
                  description: הצעות שלא בוצעו (reflection בלבד)
                  items: { type: string }
                patterns:
                  type: array
                  description: דפוסים חוזרים (reflection בלבד)
                  items: { type: string }
                suggestion:
                  type: string
                  description: הצעה לשיפור (reflection בלבד)
                insight:
                  type: string
                  description: תובנה מרכזית לשבוע הבא (reflection בלבד)
              required:
                - type
                - date
      responses:
        '200':
          description: נשלח בהצלחה
