openapi: 3.1.0
info:
  title: Google Sheets Logger
  description: Plugin לשליחת תיעוד ל-Google Sheets ולקריאת תובנות קיימות לצורך רפלקציה מערכתית.
  version: 1.0.2
servers:
  - url: https://gpt-to-sheets.sapirubner10.workers.dev
paths:
  /:
    post:
      summary: שלח תובנה או רפלקציה
      operationId: sendLog
      description: >
        תובנות נשלחות לגיליון (type: log).
        רפלקציות (type: reflection) אינן נשלחות — רק נשמרות ברמת GPT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [log, reflection]
                date:
                  type: string
                title:
                  type: string
                content:
                  type: string
                category:
                  type: string
                source:
                  type: string
                mode:
                  type: string
                track:
                  type: string
                  enum: [כן, לא]
                engines_used:
                  type: object
                  properties:
                    Verifier: { type: string }
                    Critique: { type: string }
                    Reflection: { type: string }
                    Innovation: { type: string }
                inactive_engines:
                  type: array
                  items: { type: string }
                ignored_suggestions:
                  type: array
                  items: { type: string }
                patterns:
                  type: array
                  items: { type: string }
                suggestion:
                  type: string
                insight:
                  type: string
              required:
                - type
                - date
      responses:
        "200":
          description: נשלח בהצלחה או נשמר ברמת GPT בלבד

  /read:
    get:
      summary: קרא תובנות מהגיליון
      operationId: readLogs
      responses:
        "200":
          description: רשימת תובנות קיימות בפורמט JSON
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
